### ISSUE TITLE
pip3 install -r requirements.txt  error

### ISSUE THREAD

**Issue by xuerq** [devsisters/multi-speaker-tacotron-tensorflow#6]
Thanks for this great job . the samples are really good
But had a problem when install dependency at the very beginning

```shell
pip3 install -r requirements.txt

Collecting jamo==0.4.0 (from -r requirements.txt (line 57))
  Using cached jamo-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>      File "/tmp/pip-build-ngvu7alg/jamo/setup.py", line 11, in <module>
        long_description = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 701: ordinal not in range(128)
```

**Comment by carpedm20** [comment]
Did you tried with python 3.6?

**Comment by xuerq** [comment]
Try to install with python 3.6

pip3.6 install jamo
```shell
Collecting jamo
  Using cached jamo-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_9q0ntzr/jamo/setup.py", line 11, in <module>
        long_description = f.read()
      File "/root/TF_PY3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 701: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_9q0ntzr/jamo/

```

easy_install-3.6  jamo
```shell
Searching for jamo
Reading https://pypi.python.org/simple/jamo/
Downloading https://pypi.python.org/packages/1b/52/7d77bcdfe5671636ccd4f8afcc4f61f80c70fe636ec4710b61ac4ada6c78/jamo-0.4.0.tar.gz#md5=9aa760dde44c303ed9d5fe2cd0ee68f9
Best match: jamo 0.4.0
Processing jamo-0.4.0.tar.gz
Writing /tmp/easy_install-dcyqcvyq/jamo-0.4.0/setup.cfg
Running jamo-0.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dcyqcvyq/jamo-0.4.0/egg-dist-tmp-yszk8ja7
Traceback (most recent call last):
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-dcyqcvyq/jamo-0.4.0/setup.py", line 11, in <module>
  File "/root/TF_PY3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 701: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/TF_PY3.6/bin/easy_install-3.6", line 11, in <module>
    sys.exit(main())
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 2279, in main
    **kw
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/root/TF_PY3.6/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-dcyqcvyq/jamo-0.4.0/setup.py", line 11, in <module>
  File "/root/TF_PY3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 701: ordinal not in range(128)

```

**Comment by xuerq** [comment]
successfully installed jamo  from source https://github.com/JDongian/python-jamo
closed
